### ISSUE TITLE
homework review completed

### ISSUE THREAD

**Issue by hatelove** [zeroade/TDDHomeWork1#1]
有兩個地方需要調整：
1. var testcase = new PagingGroup(); 
   建議變數名稱改成 **target** 或是 **sut**
2. 兩個 assertion 都寫錯了。
   CollectionAssert.AreNotEquivalent(expected, actual);
   應該改成 **AreEqual()** 因為在這邊順序也很重要。

**Comment by zeroade** [comment]
感謝指正

**Comment by hatelove** [comment]
Review completed.

這邊也提供我的 sample solution 給您參考一下：http://bit.ly/91-tdd-day1-homework-solution
第一版只支援 Product, 第二版則使用 extension method + generic + lambda 來支援任意型別。
